### ISSUE TITLE
Configmaps detected are used by managed kubernetes 

### ISSUE THREAD

**Issue by nanthinimuniapan** [yonahd/orphaned-configmaps#2]
Hi there,

One of the config map detected in 'kube-system' called 'aws-auth' is actually being used by AWS EKS for user authentication. Is there a specific pattern this tool looks for.

**Comment by yonahd** [comment]
Hi @nanthinimuniapan 
The tool looks for configmaps used by pods or containers. I'm assuming this configmap is not consumed by either AFAIK.
To support configmaps like this I'll create an exceptions file for skipping these types of configmaps.

**Comment by yonahd** [comment]
I added support for the exceptions file and put aws-auth as the first input there.
If there are any other exceptions you can think of please feel free to contribute.
